"""Unit tests for src/utils/fit_reader.py.

Tests use synthetic .fit.gz files generated by tests/fixtures/fit_generator.py
so that no real FIT files are needed.
"""

import gzip
import io
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from src.utils.fit_reader import (
    RECORD_FIELDS,
    compute_elapsed_seconds,
    get_activity_id_from_filename,
    parse_fit_file,
)


class TestParseRealFitFile:
    """Tests that parse synthetic but fully valid .fit.gz files."""

    def test_returns_dataframe(self, easy_run_fit_gz):
        df = parse_fit_file(easy_run_fit_gz)
        assert isinstance(df, pd.DataFrame)

    def test_has_expected_columns(self, easy_run_fit_gz):
        df = parse_fit_file(easy_run_fit_gz)
        # Core columns should always be present
        for col in ("timestamp", "heart_rate", "speed", "distance", "cadence"):
            assert col in df.columns, f"Missing column: {col}"

    def test_row_count_matches_duration(self, easy_run_fit_gz):
        df = parse_fit_file(easy_run_fit_gz)
        # 3600-second run → ~3600 rows (±a few for header records)
        assert 3500 < len(df) <= 3700

    def test_timestamps_are_utc_datetimes(self, easy_run_fit_gz):
        df = parse_fit_file(easy_run_fit_gz)
        assert pd.api.types.is_datetime64_any_dtype(df["timestamp"])
        # UTC-aware
        assert df["timestamp"].dt.tz is not None

    def test_timestamps_monotonically_increasing(self, easy_run_fit_gz):
        df = parse_fit_file(easy_run_fit_gz)
        diffs = df["timestamp"].diff().dropna()
        assert (diffs >= pd.Timedelta(0)).all()

    def test_cadence_doubled(self, easy_run_fit_gz):
        """fit_reader multiplies per-foot cadence × 2 for total SPM."""
        df = parse_fit_file(easy_run_fit_gz)
        # The generator writes per-foot ~88; after ×2 → ~176 spm
        valid = df["cadence"].dropna()
        assert valid.mean() > 100, "Cadence should be total SPM (doubled from per-foot)"

    def test_lat_lon_in_degrees(self, easy_run_fit_gz):
        df = parse_fit_file(easy_run_fit_gz)
        lat = df["position_lat"].dropna()
        lon = df["position_long"].dropna()
        if not lat.empty:
            assert lat.abs().max() < 180.0, "Latitude should be in degrees, not semicircles"
            assert lon.abs().max() < 180.0

    def test_enhanced_altitude_takes_precedence(self, easy_run_fit_gz):
        """parse_fit_file merges enhanced_altitude into altitude and drops the column."""
        df = parse_fit_file(easy_run_fit_gz)
        assert "enhanced_altitude" not in df.columns
        alt = df["altitude"].dropna()
        if not alt.empty:
            # Synthetic run starts at ~50 m; altitude should be near there
            assert 0 < alt.mean() < 5000

    def test_speed_in_ms(self, easy_run_fit_gz):
        df = parse_fit_file(easy_run_fit_gz)
        spd = df["speed"].dropna()
        # Base speed ~3.3 m/s; should not be ~3300 (mm/s)
        assert 1.0 < spd.mean() < 10.0

    def test_distance_in_meters(self, easy_run_fit_gz):
        df = parse_fit_file(easy_run_fit_gz)
        dist = df["distance"].dropna()
        assert dist.max() > 1000, "1-hour run should cover > 1000 m"
        assert dist.max() < 100000, "Should not be in cm"

    def test_parse_interval_run(self, interval_run_fit_gz):
        df = parse_fit_file(interval_run_fit_gz)
        assert not df.empty
        spd = df["speed"].dropna()
        # Interval run should have higher max speed than easy run
        assert spd.max() > 4.0

    def test_parse_long_run(self, long_run_fit_gz):
        df = parse_fit_file(long_run_fit_gz)
        dist = df["distance"].dropna()
        # 30 km run
        assert dist.max() > 25000


class TestComputeElapsedSeconds:
    def test_starts_at_zero(self, easy_run_fit_gz):
        df = parse_fit_file(easy_run_fit_gz)
        elapsed = compute_elapsed_seconds(df)
        assert elapsed.iloc[0] == pytest.approx(0.0)

    def test_monotonically_increasing(self, easy_run_fit_gz):
        df = parse_fit_file(easy_run_fit_gz)
        elapsed = compute_elapsed_seconds(df)
        assert (elapsed.diff().dropna() >= 0).all()

    def test_duration_matches_row_count(self, easy_run_fit_gz):
        df = parse_fit_file(easy_run_fit_gz)
        elapsed = compute_elapsed_seconds(df)
        # 3600 s run → elapsed[-1] should be ~3599 s
        assert elapsed.iloc[-1] == pytest.approx(3599.0, abs=5.0)

    def test_all_nan_timestamps_returns_range(self):
        df = pd.DataFrame({"timestamp": [pd.NaT, pd.NaT, pd.NaT]})
        elapsed = compute_elapsed_seconds(df)
        assert list(elapsed) == [0.0, 1.0, 2.0]


class TestGetActivityIdFromFilename:
    def test_standard_strava_filename(self):
        assert get_activity_id_from_filename("activities/1922813233.fit.gz") == "1922813233"

    def test_plain_fit(self):
        assert get_activity_id_from_filename("activities/9876543.fit") == "9876543"

    def test_non_numeric_returns_none(self):
        assert get_activity_id_from_filename("activities/my_run.fit.gz") is None

    def test_empty_string_returns_none(self):
        assert get_activity_id_from_filename("") is None

    def test_just_number(self):
        assert get_activity_id_from_filename("1234567.fit.gz") == "1234567"
